from flask import Flask,jsonify

def nftCalc():
    Authentication_n_Access_Control = 1
    GasLimits_n_Optimization = 0
    Reentrancy_Attacks = 1
    Malicious_External_Calls = 0
    Integer_Over_Underflow = 1
    Malicious_Input_Data = 1
    Time_Manipulation = 1
    Cold_Storage = 1
    Multi_Signature1 = 1
    Hierarchical_Deterministic_Wallets = 1
    Key_Management_Services = 1
    Hot_Wallets = 1
    Proof_of_Work = 1
    Proof_of_Stake = 1
    Byzantine_Fault_Tolerance = 1
    Delegated_Proof_of_Stake = 1
    Proof_of_Authority = 1
    Public_n_Private_Key_Encryption = 0
    Multi_Signature2 = 1
    Access_Control = 1
    Cryptography1 = 1
    Private_Keys = 1
    Multi_Signature3 = 1
    Encryption1 = 1
    Two_Factor_Authentication1 = 1
    Public_Keys = 1
    Smart_Contracts1 = 1
    Audit_Trails = 1
    Asymmetric_Encryption = 0
    Hashing = 1
    Symmetric_Encryption = 0
    Elliptic_Curve_Cryptography = 0
    Homomorphic_Encryption = 0
    Seed_Phrase_Backup = 1
    Multi_Signature_Wallets = 1
    Cold_Storage_Backup = 1
    Decentralized_Backup = 1
    Cloud_Backup = 1
    On_Chain_Transfers = 1
    Decentralized_Exchanges = 1
    Off_Chain_Transfers = 1
    Peer_to_Peer_Trading = 1
    Centralized_Exchanges = 1
    Hardware_Wallets = 1
    Paper_Wallets1 = 1
    Software_Wallets = 1
    Web_Wallets = 1
    Brain_Wallets = 1
    Ledger = 1
    Trezor = 1
    MetaMask = 1
    Trust_Wallet = 1
    Coinbase_Wallet = 1
    Atomic_Wallet = 1
    My_Ether_Wallet = 1
    Paper_Wallet2 = 1111111111111
    Smart_Contract_Security = 1
    Escrow_Services1 = 1
    KYC_AML_Compliance = 1
    Two_Factor_Authentication2 = 1
    Encryption2 = 1
    Two_Factor_Authentication3 = 1
    Secure_Socket_Layer_Certificate = 1
    Data_Protection_Policies = 1
    Privacy_Notices = 1
    Custodial_Insurance = 1
    Cyber_Liability_Insurance = 1
    Theft_Fraud_Insurance = 1
    Physical_Damage_Loss_Insurance = 1
    Errors_Omissions_Insurance = 1
    KYC_AML = 1
    Securities_Exchange_Commission_Compliance = 1
    IP_Compliance = 1
    Consumer_Protection_Compliance = 1
    Tax_Compliance = 1
    Transaction_Fees = 1
    Withdrawal_Fees = 1
    Listing_Fees = 1



    Minting_Fees=1
    Subscription_Fees=1111111111
    Cryptographic_verification=1
    Content_addressing1=1
    Distributed_storage=1
    Data_replication=1
    Access_control=1
    Encryption3=1
    Content_addressing2=1
    Distributed_storage1=1
    Digital_signatures=1
    Firewalls_network_security=1
    Decentralized_identity=1
    Content_addressing3=1
    Distributed_storage2=1
    Redundancy_replication=1
    Pinning=1
    Chainalysis_KYT=1
    IdentityMind=1
    Sumsub=1
    Shufti_Pro=1
    Smart_contract_protocols=1
    Escrow_services2=1
    Insurance_providers=1
    Arbitration_services=1